### ISSUE TITLE
Insert boat name on main page

### ISSUE THREAD

**Issue by R-Sylvia** [hinnerkweiler/sail4oxygenmobile#14]
It would be helpful if the boatname could be inserted next to the position data. Especially if one phone is used by severeal citizen scientists on different boats. Also to just check if it had been set correctly.

It would be great to keep the option to set the boatname in the settings and display the set name as default but in a text input form where it can be changed. The newly inserted name should then be used as the set name.

**Comment by hinnerkweiler** [comment]
<img width="496" alt="Screenshot 2024-02-11 at 01 13 01" src="https://github.com/hinnerkweiler/sail4oxygenmobile/assets/18248862/52746ddb-7986-4443-b035-4af20c24a3a8">

<img width="412" alt="Screenshot 2024-02-11 at 01 12 43" src="https://github.com/hinnerkweiler/sail4oxygenmobile/assets/18248862/26648489-81ee-4785-8298-bfd2a07e02c1">
